# Generated by Django 5.0 on 2024-01-13 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0003_images_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Filter_Price',
        ),
        migrations.DeleteModel(
            name='Filter_Price',
        ),
    ]
