# Generated by Django 5.0 on 2024-01-28 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0006_order_paid_order_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_id',
        ),
    ]
