# Generated by Django 5.0 on 2024-01-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0008_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='logo',
            field=models.ImageField(upload_to='Banner_images/img'),
        ),
    ]
