# Generated by Django 5.0 on 2024-01-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0010_alter_banner_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='logo',
            field=models.ImageField(upload_to='Banner_Images/img'),
        ),
    ]
