# Generated by Django 5.0 on 2024-01-29 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0012_alter_banner_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='logo',
            field=models.ImageField(upload_to='Product_images/img'),
        ),
    ]
